load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_redis_redis",
    build_file = "//redis:BUILD.redis",
    urls = ["https://github.com/redis/redis/archive/refs/tags/6.2.6.tar.gz"],
    sha256 = "5d452038e346b5f31d7d277a41a4ec583bc8bf04403db620403638f79bdda891",
    strip_prefix = "redis-6.2.6",
)

http_archive(
    name = "sqlite4java",
    build_file = "//third_party:BUILD.sqlite4java",
    integrity = "sha256-zsZtCvre6it1fzl30RBHO15j2a5fbIKCZSKS7YPgPnw=",
    strip_prefix = "sqlite4java-7b55b3eab6901a0e49d6e1129431fa92c4206c0b",
    url = "https://github.com/ganadist/sqlite4java/archive/7b55b3eab6901a0e49d6e1129431fa92c4206c0b.tar.gz",
)

load("//mysql:repositories.bzl", "mysql_repositories")
mysql_repositories()
