load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_redis_redis",
    build_file = "//redis:BUILD.redis",
    sha256 = "23ae46360514b25fa596ac2b3140ccb93282c2a16fe5f6d8a4d3e833610d66ac",
    strip_prefix = "redis-6.2.14",
    urls = ["https://github.com/redis/redis/archive/refs/tags/6.2.14.tar.gz"],
)

http_archive(
    name = "sqlite4java",
    build_file = "//third_party:BUILD.sqlite4java",
    integrity = "sha256-zsZtCvre6it1fzl30RBHO15j2a5fbIKCZSKS7YPgPnw=",
    strip_prefix = "sqlite4java-7b55b3eab6901a0e49d6e1129431fa92c4206c0b",
    url = "https://github.com/ganadist/sqlite4java/archive/7b55b3eab6901a0e49d6e1129431fa92c4206c0b.tar.gz",
)

load("//mysql:repositories.bzl", "mysql_repositories")

mysql_repositories()
