load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "runner",
    srcs = [
        "pgroup_unix.go",
        "pgroup_windows.go",
        "runner.go",
        "service_instance.go",
        "topo.go",
    ],
    importpath = "rules_itest/runner",
    visibility = ["//visibility:public"],
    deps = [
        "//logger",
        "//runner/topological",
        "//svclib",
    ],
)

go_test(
    name = "runner_test",
    srcs = ["runner_test.go"],
    embed = [":runner"],
    deps = ["//svclib"],
)
